### ISSUE TITLE
Replace regex HTML parsing with BS4 implementation.

### ISSUE THREAD

**Issue by CYBERDEViLNL** [marekjm/diaspy#39]
I'd like to replace the regex HTML parsing with a BeautifulSoup implementation. I think it's less sensitive to changes.

Con could be that it requires another lib.

Please share your opinions.

**Comment by marekjm** [comment]
You're calling the shots now, so you can take the code in whatever direction you like.

If you decide to go with Beautiful Soup, I would advise you to at least keep the stdlib-only fallback for when the extra lib is not available. You can always display a message informing the user that tthe lib would work better if they installed xyz lib.

I *hope* that D\* will one day expose a real API so that you won't have to make these tradeoffs ;-)

**Comment by marekjm** [comment]
No problem, I'm happy to help :-) You're doing a great job keeping diaspy alive!
